services:
  search-media:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_DRIVE_SERVICE_ACCOUNT_CREDENTIALS=${GOOGLE_DRIVE_SERVICE_ACCOUNT_CREDENTIALS}
    develop:
      watch:
        - action: rebuild
          path: ./src
